# Generated by Django 5.2.7 on 2025-11-05 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_image'),
        ('story', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='stories/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, verbose_name='Havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='StoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Savol')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('question_type', models.CharField(choices=[('radio', 'Bitta javob tanlash (Radio)'), ('checkbox', 'Bir nechta javob tanlash (Checkbox)'), ('text', 'Matn kiritish')], default='radio', max_length=10, verbose_name='Savol turi')),
                ('order', models.IntegerField(default=1, verbose_name='Tartib raqami')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='story.story')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('story', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Javob varianti')),
                ('order', models.IntegerField(default=1, verbose_name='Tartib raqami')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='story.storyquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StorySurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name="To'ldirildi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foydalanuvchi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "So'rovnoma javoblar",
                'verbose_name_plural': "So'rovnoma javoblar",
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Matn javob')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='story.storysurveyresponse')),
                ('selected_options', models.ManyToManyField(blank=True, to='story.questionoption', verbose_name='Tanlangan variantlar')),
            ],
        ),
        migrations.DeleteModel(
            name='StoryModel',
        ),
        migrations.DeleteModel(
            name='StoryTestModel',
        ),
    ]
